### ISSUE TITLE
Is the Action Hooks example correct?

### ISSUE THREAD

**Issue by PurpleEdge2214** [directus/docs#31]
https://github.com/directus/docs-v7/blob/master/extensions/hooks.md#create-an-action-hook

Should an action hook be inside the "actions" array? My experiments in placing a function there results in a runtime "internal server error", seemingly unrelated to the code?

```
    'hooks' => [
        'actions' => [
          'item.create.suburbs' => function ($data, $collectionName) {
             $content = 'New article was created with the title: ' . $data['title'];
              // pesudo function
              // notify('admin@example.com', 'New Article', $content);
          }
        ],
        'filters' => [
          'item.create.tnbusers:before' => function (\Directus\Hook\Payload $payload) {
            $payload->set('uuid', \Directus\generate_uuid4());

            return $payload;
          }
        ],

```

**Comment by WellingGuzman** [comment]
@PurpleEdge2214 There's two thing in your example:

- Missing the last `],`
- the `actions` example doesn't required the second parameter. (_Error in the documentation_)

It should be like this:

```php
'hooks' => [
    'actions' => [
        'item.create.suburbs' => function ($data, $collectionName) {
            $content = 'New article was created with the title: ' . $data['title'];
            // pesudo function
            // notify('admin@example.com', 'New Article', $content);
        }
    ],
    'filters' => [
        'item.create.tnbusers:before' => function (\Directus\Hook\Payload $payload) {
        $payload->set('uuid', \Directus\generate_uuid4());

        return $payload;
        }
    ],
],
```

**Comment by WellingGuzman** [comment]
Example fixed by https://github.com/directus/docs-v7/commit/e37b4854e2d3aca4613bf5546bcdf9cec1f6e13c

**Comment by PurpleEdge2214** [comment]
You're still not showing it with an "actions", should it be...

Create an Action Hook
```
'hooks' => [
  'item.create.articles' => function ($data, $collectionName) {
    $content = 'New article was created with the title: ' . $data['title'];
    // pesudo function
    notify('admin@example.com', 'New Article', $content);
  }
]

```
or

Create an Action Hook
```
'hooks' => [
  'actions': {
    'item.create.articles' => function ($data, $collectionName) {
      $content = 'New article was created with the title: ' . $data['title'];
      // pesudo function
      notify('admin@example.com', 'New Article', $content);
    }
  }
]
```

**Comment by WellingGuzman** [comment]
@PurpleEdge2214 the second example is correct, I just updated some of the examples on hooks that were missing these structure.

This way is correct:

```php
'hooks' => [
    'actions' => [
        'item.create.suburbs' => function ($data) {
            $content = 'New article was created with the title: ' . $data['title'];
            // pesudo function
            // notify('admin@example.com', 'New Article', $content);
        }
    ],
    'filters' => [
        'item.create.tnbusers:before' => function (\Directus\Hook\Payload $payload) {
        $payload->set('uuid', \Directus\generate_uuid4());

        return $payload;
        }
    ],
],
```

Where are you trying to add the hooks?

**Comment by PurpleEdge2214** [comment]
Thanks Welling, I'm just trying to learn how it works! <g>

It would be a great example if you could show how an action hook writes to the error log? <hint><g>

**Comment by WellingGuzman** [comment]
@PurpleEdge2214 the hook doesn't write any error logs, it's the API that catches the exceptions and write them to the logs.

What are you trying to accomplish?

Ref: [src/core/Directus/Application/ErrorHandlers/ErrorHandler.php](https://github.com/directus/api/blob/master/src/core/Directus/Application/ErrorHandlers/ErrorHandler.php#L188)

**Comment by PurpleEdge2214** [comment]
Hi Welling, as I said, I'm just trying to learn how Directus works. Writing to a log e.g. the error log, when a record is processed by a filter hook seemed like an easy example to demonstrate the functionality of a filter hook - I thought it might be a bit easier than sending an email from my local server, and more practical.

I might want to put a lot of data validation in the hooks, additional to the regex validation available in the Directus App, so learning how hooks work seemed like a good starting place.

I'll keep playing around.

**Comment by WellingGuzman** [comment]
As the hook are kind of a playground where the user create custom functionalities, the hook doesn't write code itself, but if the app catches the exception it will log that error.

Otherwise the user are responsible for the code in their hooks, if they want to catch those exceptions they need to do it in their custom code. I added an example in the docs on how to catch and write to logs using the same Directus API logger.

Ref: https://github.com/directus/docs/blob/master/extensions/hooks.md#error-logs.

**Comment by WellingGuzman** [comment]
Also I added an example on to validate data before is inserted in to collection.

Ref: https://github.com/directus/docs/blob/master/extensions/hooks.md#validate-data

These are example on how to do it, the user have the option to do this In their own way.

**Comment by PurpleEdge2214** [comment]
Thanks, very useful!

**Comment by thakurPooja2494** [comment]
hey!!

how can we pass query parameters in webhook of direct us..(not in php file)

**Comment by rijkvanzanten** [comment]
@thakurPooja2494 that seems unrelated to the OP, but just put `?whatever=value` in the endpoint field of the webhook

**Comment by thakurPooja2494** [comment]
@rijkvanzanten  hey cab you please help me out to know how to pass collection field name as a query param in web hook URL from the direct us UI not from the code.. i am attaching the image
![image](https://user-images.githubusercontent.com/64476559/80590797-27e0c680-8a3a-11ea-9a61-042a289eb493.png)
